### ISSUE TITLE
Binaries do not work

### ISSUE THREAD

**Issue by paperboyo** [jibsen/pngquant-winbuild#3]
Thanks a lot for providing this!

I definitely do not want it to turn into a programming lesson! Just wanted to say that neither binary works for me on latest Win10x64. Both, when asked why, say:

```
Untitled-1.png:
  read 151KB file
Skipped 1 file out of a total of 1 file.
```

And make says:

```
\pngquant-winbuild>make
gcc -Wall -O2 -msse -fopenmp -flto -fvisibility=hidden -DNDEBUG -D_LARGEFILE64_SOURCE=1 -DUSE_SSE=1 -DUSE_LCMS=1 -DIMAGEQUANT_EXPORTS -I zlib -I libpng -I lcms2/include -fno-math-errno -funroll-loops -fomit-frame-pointer -fexcess-precision=fast -c -o pngquant/pngquant.o pngquant/pngquant.c
pngquant/pngquant.c:84:17: fatal error: omp.h: No such file or directory
 #include <omp.h>
                 ^
compilation terminated.
make: *** [Makefile:56: pngquant/pngquant.o] Error 1
```

Thanks anyway, I will figure out a way!

**Comment by jibsen** [comment]
You're right, there's something entirely wrong.

**Comment by jibsen** [comment]
I think I found the issue. I've added a workaround and updated the binaries.

**Comment by paperboyo** [comment]
Thanks a lot, @jibsen! The binaries work correctly now (they leave untagged images untagged and correctly - if silently and without giving users choice - convert all profiles to sRGB and tag these images).

I still can’t compile, but I’m sure the problem is on my side. Closing and big thanks again!
